--Inner Join Exercise
--1.	Select Student full names and the course ID's they are registered in.
--2.	Select the Staff full names and the Course ID’s they teach
--3.	Select all the Club ID's and the Student full names that are in them
--4.	Select the Student full name, courseID's and marks for studentID 199899200.
--5.	Select the Student full name, course names and marks for studentID 199899200.
--6.	Select the CourseID, CourseNames, and the Semesters they have been taught in
--7.	What Staff Full Names have taught IT System Administration?
--8.	What is the course list for student ID 199912010 in semestercode A100. Select the Students Full Name and the CourseNames.
--9.	What are the Student Names, courseID's that have Marks > 80?

