USE CreateTable

DROP TABLE IF EXISTS Grade
DROP TABLE IF EXISTS Activity
DROP TABLE IF EXISTS Course
DROP TABLE IF EXISTS Student
DROP TABLE IF EXISTS Club

CREATE TABLE Course (
	CourseID CHAR(6) NOT NULL 
		CONSTRAINT PK_Course PRIMARY KEY CLUSTERED
,	CourseName VARCHAR(40) NOT NULL
,	[Hours] SMALLINT NULL 
		CONSTRAINT CK_HoursGreaterThanZero CHECK ([Hours] > 0)
,	NoOfStudents SMALLINT NULL
		CONSTRAINT CK_NumStudentsAtLeastZero CHECK (NoOfStudents >= 0)
)

CREATE TABLE Student (
	StudentID INT NOT NULL
		CONSTRAINT PK_Student PRIMARY KEY CLUSTERED
,	StudentFirstName VARCHAR(40) NOT NULL
,	StudentLastName VARCHAR(40) NOT NULL
,	GenderCode CHAR(1) NOT NULL
		CONSTRAINT CK_GenderCode CHECK (GenderCode LIKE '[FMX]')
,	Address VARCHAR(30) NULL
,	BirthDate DATETIME NULL
,	PostalCode CHAR(6) NULL 
		CONSTRAINT CK_PostalCode CHECK (PostalCode LIKE '[A-Z][0-9][A-Z][0-9][A-Z][0-9]')
,	AvgMark DECIMAL(4,1) NULL
		CONSTRAINT CK_AvgMark CHECK (AvgMark BETWEEN 0 AND 100)
,	NoOfCourses SMALLINT NULL
		CONSTRAINT CK_NoOfCourse CHECK (NoOfCourses >= 0)
		CONSTRAINT DF_NoOfCourses DEFAULT 0
)

CREATE TABLE Grade (
	StudentID INT NOT NULL
		CONSTRAINT FK_GradeToStudent FOREIGN KEY REFERENCES Student (StudentID) 
,	CourseID CHAR(6) NOT NULL 
		CONSTRAINT FK_GradeToCourse FOREIGN KEY REFERENCES Course (CourseID)
,	Mark SMALLINT NULL
		CONSTRAINT CK_MarkBetweenZeroAndOneHundred CHECK (Mark BETWEEN 0 AND 100)
		CONSTRAINT DF_Mark DEFAULT 0
,	CONSTRAINT PK_Grade PRIMARY KEY CLUSTERED (StudentID, CourseID)
)

CREATE TABLE Club (
	ClubID INT NOT NULL
		CONSTRAINT PK_Club PRIMARY KEY CLUSTERED
,	ClubName VARCHAR(50) NOT NULL
)

CREATE TABLE Activity (
	StudentID INT NOT NULL
		CONSTRAINT FK_ActivityToStudent
		FOREIGN KEY REFERENCES Student (StudentID)
,	ClubID INT NOT NULL
		CONSTRAINT FK_ActivityToClub
		FOREIGN KEY REFERENCES Club (ClubID)
,	CONSTRAINT PK_Activity PRIMARY KEY CLUSTERED (StudentID, ClubID)
)